apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blog-service-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: gestion-blog
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /piblog/actuator/prometheus
      interval: 15s