apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
  namespace: project-offer
data:
  application.properties: |
    spring.application.name=ProjetPI
    spring.datasource.url=jdbc:mysql://mysql:3306/projectDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    spring.datasource.username=root
    spring.datasource.password=
    spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto=update
    server.port=8045
    eureka.client.enabled=false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: project-offer
data:
  SPRING_PROFILES_ACTIVE: "dev"