apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-offer-backend
  namespace: project-offer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-offer-backend
  template:
    metadata:
      labels:
        app: project-offer-backend
    spec:
      containers:
      - name: backend
        image: amounete/project-offer-backend:latest
        ports:
        - containerPort: 8045
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        env:
        - name: SPRING_CONFIG_LOCATION
          value: "file:/app/config/application.properties"
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        # Probes désactivées
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      volumes:
      - name: config
        configMap:
          name: backend-config