spring.application.name=ProjetPI
spring.datasource.url=jdbc:mysql://localhost:3306/Projetfreelancer?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8081
#server.servlet.context-path=/pi

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# FORCER L'UTILISATION DE LOCALHOST
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}
spring.cloud.config.import-check.enabled=false
spring.cloud.config.fail-fast=true