spring.application.name=API-gateway
# Route vers Event Service


server.port=8085
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


spring.cloud.gateway.routes[0].id=event-service
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/events/**

Gateway :
logging.level.org.springframework.cloud.gateway=DEBUG 
logging.level.reactor.netty.http.client=DEBUG

