apiVersion: v1
kind: ConfigMap
metadata:
  name: marketing-config
data:
  db-url: "jdbc:mysql://marketing-db:3306/marketing?createDatabaseIfNotExist=true"
---
apiVersion: v1
kind: Secret
metadata:
  name: marketing-secret
type: Opaque
stringData:
  db-username: "root"
  db-password: ""
