apiVersion: v1
kind: ConfigMap
metadata:
  name: communication-config
data:
  db-url: "jdbc:mysql://communication-db:3306/Communication?createDatabaseIfNotExist=true"
---
apiVersion: v1
kind: Secret
metadata:
  name: communication-secret
type: Opaque
stringData:
  db-username: "root"
  db-password: ""
