server.port=8201

spring.application.name=core-service

eureka.client.service-url.defaultZone=http://localhost:8150/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info,metrics,env,configprops
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.info.build.enabled=true
management.info.git.enabled=true

spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=3000
