spring.application.name=OffreGateway
server.port=8085
# Configuration des routes dynamiques avec Eureka
spring.cloud.gateway.routes[0].id=PROJETPI
spring.cloud.gateway.routes[0].uri=lb://PROJETPI
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/projects/**
# Eureka - Configuration pour forcer localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# FORCER L'UTILISATION DE LOCALHOST
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG