server.port=8150

spring.application.name=discovery-service

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Monitoring endpoints
management.endpoints.web.exposure.include=health,info,metrics,env,configprops
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.info.build.enabled=true
management.info.git.enabled=true

